<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Fyreplace</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2270" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NSwag.MSBuild" Version="14.7.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Sentry" Version="6.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <WarningLevel>9999</WarningLevel>
  </PropertyGroup>

  <Target Name="NSwag" Outputs="Services\ApiClient.g.cs" BeforeTargets="PrepareForBuild">
    <Exec Command="$(NSwagExe) openapi2csclient /Input:Services\openapi.yaml /Output:$(IntermediateOutputPath)Services\ApiClient.g.cs /GenerateClientInterfaces:true /Namespace:Fyreplace.Services /ClassName:ApiClient" />
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)Services\ApiClient.g.cs" />
    </ItemGroup>
  </Target>
</Project>