name: Publishing

on:
  push:
    branches:
      - develop
      - hotfix/*
      - release/*
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: windows-latest
    environment: microsoft-store
    strategy:
      matrix:
        architecture:
          - x86
          - x64
          - arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-${{ matrix.architecture }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.architecture }}-nuget-

      - name: Set Up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Prepare files
        run: .\prepare.bat

      - name: Restore Nuget packages
        run: msbuild /t:Restore /p:Platform=${{ matrix.architecture }}

      - name: Build app
        env:
          PackageName: ${{ vars.PACKAGE_NAME }}
          PackagePublisher: ${{ vars.PACKAGE_PUBLISHER }}
          PackagePublisherName: ${{ vars.PACKAGE_PUBLISHER_NAME }}
          SentryDsn: ${{ secrets.SENTRY_DSN}}
          SentryOrg: ${{ vars.SENTRY_ORG }}
          SentryProject: ${{ vars.SENTRY_PROJECT }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          msbuild /t:Build `
            /p:Configuration=Release `
            /p:Platform=${{ matrix.architecture }} `
            /p:GenerateAppxPackageOnBuild=True `
            /p:UapAppxPackageBuildMode=StoreUpload `
            /p:AppxPackageDir=AppPackages\

      - name: Simplify export path
        run: move .\Fyreplace\AppPackages\* .\Fyreplace\AppPackages\Result

      - name: Upload MSIX
        uses: actions/upload-artifact@v4
        with:
          name: Fyreplace.unsigned.${{ matrix.architecture }}.msix
          path: Fyreplace\AppPackages\Result\*.msix
          if-no-files-found: error
